# Generated by Django 3.2.3 on 2021-10-01 16:27

from django.db import migrations, models
import django.utils.timezone
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=0, max_length=255)),
                ('desciption', models.CharField(default=0, max_length=2047)),
                ('photo', models.ImageField(null=True, upload_to=polls.models.upload_location)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
