# Generated by Django 3.2.3 on 2021-10-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='desciption',
        ),
    ]
