# Generated by Django 3.2.3 on 2021-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_sujet_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='matiere',
            field=models.CharField(choices=[('Fr', 'Francais'), ('P', 'Physique'), ('M', 'Maths')], default='Fr', max_length=2),
        ),
    ]
