# Generated by Django 3.2.3 on 2021-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sujet_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='titre',
        ),
        migrations.AlterField(
            model_name='sujet',
            name='matiere',
            field=models.CharField(choices=[('Fr', 'Francais'), ('Ang', 'Anglais'), ('Phy', 'Physique Chimie'), ('Mat', 'Maths'), ('SI', "Science de l'ingénieur")], default='Fr', max_length=3),
        ),
    ]
