# Generated by Django 3.2.3 on 2021-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211002_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='matiere',
            field=models.CharField(choices=[('Mat', 'Maths'), ('Phy', 'Physique Chimie'), ('SI', "Science de l'ingénieur"), ('Ang', 'Anglais'), ('Fr', 'Francais')], default='Mat', max_length=3),
        ),
    ]
