# Generated by Django 3.2.3 on 2021-10-03 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_sujet_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujet',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='sujet',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
